version: "3"

services:
  #nginx-proxy:
  #  image: jwilder/nginx-proxy
  #  restart: always
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - conf:/etc/nginx/conf.d
  #    - vhost:/etc/nginx/vhost.d
  #    - html:/usr/share/nginx/html
  #    - dhparam:/etc/nginx/dhparam
  #    - certs:/etc/nginx/certs:ro
  #    - /var/run/docker.sock:/tmp/docker.sock:ro
  #  labels:
  #    - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  #letsencrypt:
  #  image: jrcs/letsencrypt-nginx-proxy-companion
  #  restart: always
  #  volumes_from:
  #    - nginx-proxy
  #  volumes:
  #    - certs:/etc/nginx/certs:rw
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #  environment:
  #    - DEFAULT_EMAIL=gchavez.dev.2023@gmail.com

  #duckdns:
  #  image: linuxserver/duckdns
  #  container_name: duckdns
  #  environment:
  #    - TZ=America/Santiago
  #    - "SUBDOMAINS=gestor-prestamos" #Cambiarlo!!!!
  #    - "TOKEN=3009a3c4-0c2d-4787-9ff9-498a63f6e99e" #Cambiarlo!!!!
  #    - LOG_FILE=false #optional
  #  restart: always

  basedatos:
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .bd-mysql-data:/var/lib/mysql

  #aspcore:
  #  image: gchavezdev2023/webapp_gestor_prestamos:latest
  #  depends_on:
  #    - basedatos
  #  links:
  #    - basedatos:basedatos
  #  expose:
  #    - "80"
  #  #volumes:
  #  #    - ~/netcore/app:/app
  #  #   - ~/netcore/SolucionChacoCooperativa/core-app/wwwroot/Image:/app/wwwroot/Image
  #  restart: always
  #  environment:
  #    - "ASPNETCORE_URLS=https://+:80"
  #    #Con esto se activa modo desarrollo y envia mas mensajes
  #    - "ASPNETCORE_ENVIRONMENT=Development"
  #    - "VIRTUAL_HOST=gestor-prestamos.duckdns.org" #Cambiarlo!!!!
  #    - "LETSENCRYPT_HOST=gestor-prestamos.duckdns.org" #Cambiarlo!!!!
  #    - "LETSENCRYPT_EMAIL=gchavez.dev.2023@gmail.com" #Cambiarlo!!!!
  #    #Activar HTTPS
  #    #- "ASPNETCORE_URLS=https://+;http://+"
  #    #- "ASPNETCORE_HTTPS_PORT=8001"
  #    #- "ASPNETCORE_Kestrel__Certificates__Default__Password=PalabraClaveDeCertificado"
  #    #- "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
  #    #Conexion BBDD
  #    - "ConnectionStrings:DefaultConnection=server=basedatos; port=3306; database=gestion_creditos ;user=root; password=root;"

  phpmyadmin:
    depends_on:
      - basedatos
    image: phpmyadmin/phpmyadmin
    links:
      - basedatos
    environment:
      PMA_HOST: basedatos
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
#volumes:
#  conf:
#  vhost:
#  html:
#  dhparam:
#  certs:
