version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:1.3.1-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  #Para usar el contenedor letsencrypt debe estar abierto puerto 80 y 443, sin restricciones
  #Sino el autorizador no genera el certificado para HTTPS
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:2.2.8
    container_name: letsencrypt
    depends_on:
      - duckdns
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #Importante declarlo para que se regenere el certificado cuando reinicia el conteneodr (genera bloqueo por exceso de uso).
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${mail}

  duckdns:
    image: linuxserver/duckdns:version-1c126a78
    container_name: duckdns
    environment:
      - TZ=America/Santiago
      #Cambiarlo para activar subdominio por DuckDNS
      - "SUBDOMAINS=${subdominio}"
      #Cambiarlo para activar subdominio por DuckDNS
      - "TOKEN=3009a3c4-0c2d-4787-9ff9-498a63f6e99e"
      - LOG_FILE=false #optional
    restart: always

  basedatos:
    image: mysql:8.1.0
    container_name: basedatos
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .bd-mysql-data:/var/lib/mysql

  aspcore:
    image: gchavezdev2023/webapp:latest
    container_name: aspcore
    depends_on:
      - basedatos
    links:
      - basedatos:basedatos
    expose:
      - "80" #Solo exponer 80, el proxy reverso de nginx saca por 443
    #volumes:
    #Para utilizar repositorio
    #  - ~/netcore/app:/app
    #  - ~/netcore/SolucionChacoCooperativa/core-app/wwwroot/Image:/app/wwwroot/Image
    restart: always
    environment:
      #Con esto se activa modo desarrollo y envia mas mensajes
      - "ASPNETCORE_ENVIRONMENT=Development"
      #Para activar LETENCRYPT
      - "VIRTUAL_HOST=${subdominio}.duckdns.org"
      - "LETSENCRYPT_HOST=${subdominio}.duckdns.org"
      - "LETSENCRYPT_EMAIL=${mail}"
      #Para activar solo HTTP y que el NGINX saque el trafico por 443
      - "ASPNETCORE_URLS=http://+:80"
      #Conexion BBDD
      - "ConnectionStrings:DefaultConnection=${stringconexion}"

#Visor de BD MySQL - Pesa 500MB, utilizar workbench
#  phpmyadmin:
#    depends_on:
#      - basedatos
#    image: phpmyadmin/phpmyadmin
#    links:
#      - basedatos
#    environment:
#      PMA_HOST: basedatos
#      PMA_PORT: 3306
#      PMA_ARBITRARY: 1
#    restart: always
#    ports:
#      - "8080:80"

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
